### ISSUE TITLE
Worker pool method needs to be added

### ISSUE THREAD

**Issue by yakuter** [yakuter/chanman#1]
For now, jobs are processing by 1 worker. We need to add worker pool method to make workers do the job.

User should define the worker number with options like:

```
opts := &chanman.Options{
		CallbackFn: callbackFn,
		Limit:      10,
		Worker: 5, // This will be added
	}
```

Some useful documents:
https://brandur.org/go-worker-pool
https://medium.com/code-chasm/go-concurrency-pattern-worker-pool-a437117025b1

Anyone wants to take this job?

**Comment by yusufpapurcu** [comment]
I can take this.

**Comment by yakuter** [comment]
Great @yusufpapurcu thank you.
