### ISSUE TITLE
Change the repo name

### ISSUE THREAD

**Issue by yakuter** [yakuter/chanman#5]
Chanman is a nice name but I think we deserve better. Related keywords for new name are:

channel
queue
job
worker
task

What do you think? @yusufpapurcu @halilkocaoz

**Comment by yusufpapurcu** [comment]
I think we must decide project size firstly. Are we think adding more features and methods? Or we just keep it simple and easy to depend?

I mean we can add support for writing to disk, more control for workers or compression for items. This kind of features makes this project more unique and needs unique name 😄

**Comment by yakuter** [comment]
I want to keep this repo simple. So I will create a new one which will be duplicate of this. We can add as many features as we want. Data persistent methods, compressions etc.

Let's find a new name for this new repo.

**Comment by yusufpapurcu** [comment]
I think we can say it "kudruk". This is a ancient form of "kuyruk". And "kuyruk" means queue in Turkish.

**Comment by yakuter** [comment]
Great name. I just created the repo.

https://github.com/yakuter/kudruk
